first half

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -22,7 +22,6 @@ jobs:
     docker:
       # Use the same Docker base as the project
       - image: python:3.7.3-stretch
-    
     working_directory: ~/repo
     
     steps:
@@ -40,24 +39,64 @@ jobs:
             python3 -m venv venv
             . venv/bin/activate
             make install
-            # Install hadolint
-            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
-            chmod +x /bin/hadolint
             
       - save_cache:
           paths:
             - ./venv
           key: v1-dependencies-{{ checksum "requirements.txt" }}
-
-      # run lint!
-      - run:
+            
+    test_docker:
+      docker:
+        # Use the same Docker base as the project
+        - image: python:3.7.3-stretch
+      working_directory: ~/repo
+    
+      steps:
+        - checkout
+      
+        # Download and cache dependencies
+        - restore_cache:
+            keys:
+              - v1-dependencies-{{ checksum "requirements.txt" }}
+              # fallback to using the latest cache if no exact match is found
+              - v1-dependencies-
+              
+        - run:
+          name: install dependencies
+          command: |
+            pip install --upgrade pip
+            apk add --update curl python 
+            # Install hadolint
+            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
+            chmod +x /bin/hadolint
+            
+          # run lint!
+        - run:
           name: run lint
           command: |
             . venv/bin/activate
-            make lint
+            STATUS=$(make lint)
+            if curl $STATUS_URL | grep "10.00/10"
+            then
+              exit 0
+            else
+              exit 1
+            fi
             
-      - destroy-environment
+    docker_build_upload:
+      docker:
+        - image: docker:17.05.0-ce-git
+      working_directory: ~/repo
+      
+      steps:
+        - checkout
 
+        - run:
+            name: Build application Docker image
+            command: |
+              ./run_docker.sh
+              ./upload_docker.sh
+              
   create_infrastructure:
     docker:
       - image: python:3.7-alpine3.11
@@ -67,7 +106,7 @@ jobs:
           name: install dependencies
           command: |
             pip install --upgrade pip
-            apk add --update tar gzip ansible nodejs npm curl python jq
+            apk add --update tar gzip  curl python
             pip install awscli
             curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
             mv /tmp/eksctl /usr/local/bin  
@@ -91,7 +130,7 @@ jobs:
             eksctl create cluster --name capstone --region=us-east-1
             aws eks describe-cluster --name capstone --query cluster.endpoint --output text
             eksctl get nodegroups --cluster capstone
-  
+      - destroy-environment
   configure_infrastructure:
     docker:
       # Docker image here that supports Ansible
@@ -117,6 +156,7 @@ jobs:
             URLS=$(aws ec2 describe-instances --filters "Name=tag:eks:cluster-name,Values=capstone" --query "Reservations[*].Instances[*].PublicDnsName" --output text) ;
             curl -H "Content-Type: text/plain" -H "token: HbfEaJNUXNPZ2MNx4KVzaV" --request PUT --data "$URLS" https://kvdb.io/HbfEaJNUXNPZ2MNx4KVzaV/migration_$\{CIRCLE_WORKFLOW_ID:0:7\}
             echo $URLS
+      - destroy-environment
             
   cleanup:
     docker:
@@ -133,17 +173,19 @@ jobs:
       - run:
           name: delete cluster
           command: |
-            eksctl delete nodegroup --cluster capstone --region=us-east-1
-            eksctl delete cluster --name eksctl-capstone-cluster
             aws cloudformation delete-stack --stack-name eks-capstone-cluster
 
 workflows:
   my_workflow:
     jobs:
       - build
-      - create_infrastructure:
+      - test_docker:
           requires: [build]
-      - configure_infrastructure:
-          requires: [create_infrastructure]
-      - cleanup:
-          requires: [create_infrastructure, configure_infrastructure]
+      - docker_build_upload:
+          requires: [test_docker]
+      #- create_infrastructure:
+      #    requires: [build]
+      #- configure_infrastructure:
+      #    requires: [create_infrastructure]
+      #- cleanup:
+      #    requires: [create_infrastructure, configure_infrastructure]
